import React from 'react';
import { getSession } from "next-auth/client";
import { useTranslations } from "next-intl";
import { getProfile } from "../../lib/profile";
import { UserCircleIcon } from '@heroicons/react/solid'
import Head from "next/head";
import { useState } from "react";
import Profile from "../../components/account/profile";
import Address from "../../components/account/address";
import AddressesList from "../../components/account/addressesList";
import { getCountries } from "../../lib/staff";

interface ProfileProps {
    user: any,
    addresses: any,
    countries: any;
}

function Account({session, infoData, locale} : {session:any, infoData:ProfileProps, locale:string}) {
    const t = useTranslations();

    const [activeTab, setActiveTab] = useState('profile');
    const [profileData] = useState(infoData.user);

    const handleTabClick = (e:React.MouseEvent<HTMLElement>) => {
        const target = e.target as HTMLElement;
        setActiveTab(target.id);
    }

    return (
        <>
            <Head>
                <title>Amadeo CRM - Account page</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className="container bg-white rounded-lg
                    pt-4 pb-10 m-auto mt-6 md:mt-15 lg:px-12 xl:px-16">
                <div
                    className="px-4 py-4 border-b lg:py-6 lg:pl-5 dark:border-primary-darker">
                    <h1 className="text-2xl">
                        <UserCircleIcon className="h-10 text-black" />
                        <span className="ml-3">{t('My profile')}</span>
                    </h1>
                </div>
                <div className="block">
                    {profileData.role_id === 2 && (
                        <nav className="flex flex-col sm:flex-row">
                            <button
                                id="profile"
                                onClick={handleTabClick}
                                className={`tab-header ${activeTab === 'profile' ? 'active' : ''}`}>
                                {t('My profile')}
                            </button>
                            <button
                                id="addressess"
                                onClick={handleTabClick}
                                className={`tab-header ${activeTab === 'addressess' ? 'active' : ''}`}>
                                {t('My Addressess')}
                            </button>
                        </nav>
                    )}

                </div>
                <div className="flex flex-col sm:flex-row">
                    <div className={`w-full ${activeTab !== 'profile' ? 'hidden' : ''}`}>
                        <Profile />
                    </div>
                    <div className={`w-full ${activeTab !== 'addressess' ? 'hidden' : ''}`}>
                        <AddressesList email={session.user.email || ''} />
                        <Address
                            userAddress={{country_id: '', state: '', post_code: '', address_type: '', city: '', address_line_1:'', address_line_2: '' }}
                            countriesData={infoData.countries}
                            email={session.user.email}
                            locale={locale}
                        />
                    </div>
                </div>

            </div>
        </>
    )
}

// @ts-ignore
export default Account;

export async function getServerSideProps(context:any) {
    const { req, locale } = context;
    const session = await getSession({ req });

    let infoData:ProfileProps;
    if (!session) {
        return {
            redirect: { destination: `/${locale === 'fr' ? '' : `${locale}/`}auth/signin` },
        };
    } else {
        infoData = await getProfile(session.user?.email);
        infoData.countries = await getCountries();
    }

    return {
        props: {
            session: session,
            locale: locale,
            infoData: infoData,
            messages: {
                ...require(`../../messages/auth/${locale}.json`),
                ...require(`../../messages/account/${locale}.json`),
                ...require(`../../messages/shared/${locale}.json`),
                ...require(`../../messages/errors/${locale}.json`),
            },
        },
    };
}
