import Head from 'next/head';
import { getSession } from 'next-auth/client';
import { InboxIcon } from '@heroicons/react/solid';
import React from 'react';
import { useTranslations } from 'next-intl';

export default function Index() {
    const t = useTranslations();

    return (
        <div className="h-screen bg-gray-100 overflow-hidden">
            <Head>
                <title>Amadeo CRM - Notofocations</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div
                className="container bg-white rounded-lg
                    pt-4 pb-10 m-auto mt-6 md:mt-15 lg:px-12 xl:px-16">
                <div className="px-4 py-4 border-b lg:py-6 lg:pl-5 dark:border-primary-darker">
                    <h1 className="text-2xl">
                        <InboxIcon className="h-10 text-black" />
                        <span className="ml-3">{t('My notifications')}</span>
                    </h1>
                </div>
                {/*<div className="block">*/}
                {/*    {profileData.role_id === 2 && (*/}
                {/*        <nav className="flex flex-col sm:flex-row">*/}
                {/*            <button*/}
                {/*                id="profile"*/}
                {/*                onClick={handleTabClick}*/}
                {/*                className={`tab-header ${activeTab === 'profile' ? 'active' : ''}`}>*/}
                {/*                {t('My profile')}*/}
                {/*            </button>*/}
                {/*            <button*/}
                {/*                id="addressess"*/}
                {/*                onClick={handleTabClick}*/}
                {/*                className={`tab-header ${*/}
                {/*                    activeTab === 'addressess' ? 'active' : ''*/}
                {/*                }`}>*/}
                {/*                {t('My Addressess')}*/}
                {/*            </button>*/}
                {/*        </nav>*/}
                {/*    )}*/}
                {/*</div>*/}
                <div className="flex flex-col sm:flex-row">
                    {/*<div className={`w-full ${activeTab !== 'profile' ? 'hidden' : ''}`}>*/}
                    {/*    <Profile />*/}
                    {/*</div>*/}
                    {/*<div className={`w-full ${activeTab !== 'addressess' ? 'hidden' : ''}`}>*/}
                    {/*    <AddressesList email={session.user.email || ''} />*/}
                    {/*    <Address*/}
                    {/*        userAddress={{*/}
                    {/*            country_id: '',*/}
                    {/*            state: '',*/}
                    {/*            post_code: '',*/}
                    {/*            address_type: '',*/}
                    {/*            city: '',*/}
                    {/*            address_line_1: '',*/}
                    {/*            address_line_2: ''*/}
                    {/*        }}*/}
                    {/*        countriesData={infoData.countries}*/}
                    {/*        email={session.user.email}*/}
                    {/*        locale={locale}*/}
                    {/*    />*/}
                    {/*</div>*/}
                </div>
            </div>
        </div>
    );
}

export async function getServerSideProps(context: any) {
    const { locale } = context;
    const session = await getSession(context);

    if (!session) {
        return {
            redirect: { destination: `/${locale === 'fr' ? '' : `${locale}/`}auth/signin` }
        };
    }

    return {
        props: {
            session,
            locale,
            messages: {
                ...require(`../../messages/${locale}.json`)
            }
        }
    };
}
