import Head from 'next/head';
import { getSession } from 'next-auth/client';

export default function Index({ session }: { session: any }) {
    if (!session) return <></>;

    return (
        <div className="h-screen bg-gray-100 overflow-hidden">
            <Head>
                <title>Amadeo CRM - Notofocations</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className="flex" />
        </div>
    );
}

export async function getServerSideProps(context: any) {
    const { locale } = context;
    const session = await getSession(context);

    if (!session) {
        return {
            redirect: { destination: `/${locale === 'fr' ? '' : `${locale}/`}auth/signin` }
        };
    }

    return {
        props: {
            session,
            locale,
            messages: {
                ...require(`../../messages/${locale}.json`)
            }
        }
    };
}
