import Head from 'next/head';
import { getSession } from 'next-auth/client';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
// import { useTranslations } from 'next-intl';
import { useDispatch, useSelector } from 'react-redux';
import { checkPaymentStatusAction } from '../../redux/checkout';
import { paymentStatusSelector } from '../../redux/checkout/selectors';

export default function Index({ session }: { session: any }) {
    if (!session) return null;
    const paymentStatus = useSelector(paymentStatusSelector);

    const {
        query: { hash, type }
    } = useRouter();

    const dispatch = useDispatch();

    useEffect(() => {
        dispatch(checkPaymentStatusAction(hash, type));
    }, []);

    useEffect(() => {
        if (paymentStatus) {
            if (paymentStatus === 'success') {
                location.href = `${window.location.origin}/checkout/complete`;
            }
        }
    }, [paymentStatus]);

    return (
        <>
            <Head>
                <title>Amadeo CRM - Checkout Confirmation</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className="lg:white-shadow-medium bg-white rounded-lg pr-4 pb-4 lg:pr-8 lg:pb-8 lg:mr-4 mt-10">
                <div className="flex flex-wrap items-center">
                    <div className="text-3xl font-bold text-gray-350 p-4 lg:p-8 mr-4 lg:mr-8">
                        Checkout confirmation
                    </div>
                </div>
            </div>
        </>
    );
}
export async function getServerSideProps(context: any) {
    const { locale } = context;
    const session = await getSession(context);

    if (!session) {
        return {
            redirect: { destination: `/${locale === 'fr' ? '' : `${locale}/`}auth/signin` }
        };
    }

    return {
        props: {
            session,
            locale,
            messages: {
                ...require(`../../messages/${locale}.json`)
            }
        }
    };
}
