import Head from 'next/head';
import { getSession } from 'next-auth/client';
import Image from 'next/image';

export default function Index({ session }: { session: any }) {
    if (!session) return <></>;

    return (
        <>
            <Head>
                <title>Amadeo CRM - Dashboard</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className="page-title">
                <h1 className="dashboard">
                    Welcome back, <span>Christian Z. Andrew !</span>
                </h1>
                <button className="btn-big float-right mt-4">Go live now!</button>
            </div>
            <div className="block-white-4 mr-10">
                <div className="flex flex-row flex-wrap w-full">
                    <div className="flex flex-col w-full lg:w-1/4 xl:w-1/5 justify-center align-middle">
                        <span className="font-bold text-sm text-blue-350">Total Revenue</span>
                        <div className="">
                            <Image src="/images/dashboard-card.svg" width={20} height={18} />
                            <span className="ml-3 font-bold text-gray-350 text-2xl">
                                999,999.99 €
                            </span>
                        </div>
                    </div>
                    <div className="flex flex-col w-full lg:w-1/4 xl:w-1/5 justify-center align-middle pl-4 border border-b-0 border-t-0 border-r-0">
                        <span className="font-bold text-sm text-blue-350">Customers</span>
                        <div className="">
                            <Image src="/images/dashboard-customers.svg" width={20} height={18} />
                            <span className="ml-3 font-bold text-gray-350 text-2xl">999,999</span>
                        </div>
                    </div>
                    <div className="flex flex-col w-full lg:w-1/4 xl:w-1/5 justify-center align-middle pl-4 border border-b-0 border-t-0 border-r-0">
                        <span className="font-bold text-sm text-blue-350">Invoices</span>
                        <div className="">
                            <Image src="/images/dashboard-invoices.svg" width={20} height={20} />
                            <span className="ml-3 font-bold text-gray-350 text-2xl">999,999</span>
                        </div>
                    </div>
                    <div className="flex flex-col w-full lg:w-1/4 xl:w-2/5 justify-center align-middle pl-4 border border-b-0 border-t-0 border-r-0">
                        <span className="font-bold text-sm text-blue-350">Period</span>
                        <div className="border rounded-lg block max-w-[215px]">
                            <div className="p-3 flex">
                                <Image src="/images/calendar.svg" width={20} height={18} />
                                <span className="font-bold text-sm text-blue-350 ml-2">
                                    30 Nov - 31 Dec
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="block-white-4 mr-10 mt-8">
                <div className="font-bold text-gray-350 text-base pb-4 mb-2 border border-t-0 border-l-0 border-r-0">
                    Orders <span className="text-sm text-gray-180 font-normal">(Last 30 days)</span>
                    <a className="view-all float-right mr-4">See all</a>
                </div>
                <div className="inline-block min-w-full overflow-hidden align-middle">
                    <table className="min-w-full float-table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Status</th>
                                <th>Date</th>
                                <th>Buyer</th>
                                <th>Country</th>
                                <th>Product</th>
                                <th>Total</th>
                            </tr>
                        </thead>

                        <tbody className="bg-white">
                            <tr>
                                <td className="red-yellow-gradient-text">QQ-1234Z</td>
                                <td>
                                    <span
                                        className="inline-flex px-2 text-xs font-semibold
                                        leading-5 text-green-800 bg-green-100 rounded-full">
                                        Payed
                                    </span>
                                </td>
                                <td>30 Jul, 2020</td>
                                <td>Ettiene, Clemence</td>
                                <td>FR</td>
                                <td>Entry</td>
                                <td>999,999.99 €</td>
                            </tr>
                            <tr>
                                <td className="red-yellow-gradient-text">QQ-1234Z</td>
                                <td>
                                    <span
                                        className="inline-flex px-2 text-xs font-semibold leading-5
                                        text-yellow-700 bg-yellow-100 rounded-full">
                                        Due
                                    </span>
                                </td>
                                <td>30 Jul, 2020</td>
                                <td>Ettiene, Clemence</td>
                                <td>FR</td>
                                <td>Entry</td>
                                <td>999,999.99 €</td>
                            </tr>
                            <tr>
                                <td className="red-yellow-gradient-text">QQ-1234Z</td>
                                <td>
                                    <span
                                        className="inline-flex px-2 text-xs font-semibold leading-5
                                        text-red-700 bg-red-100 rounded-full">
                                        Overdue
                                    </span>
                                </td>
                                <td>30 Jul, 2020</td>
                                <td>Ettiene, Clemence</td>
                                <td>FR</td>
                                <td>Entry</td>
                                <td>999,999.99 €</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div className="block-white-4 mr-10 mt-8">
                <div className="font-bold text-gray-350 text-base pb-4 mb-2 border border-t-0 border-l-0 border-r-0">
                    Clients
                    <span className="text-sm text-gray-180 font-normal">(Last 30 days)</span>
                    <a className="view-all float-right mr-4">See all</a>
                </div>
                <div className="inline-block min-w-full overflow-hidden align-middle">
                    <table className="min-w-full float-table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Buyer</th>
                                <th>Orders</th>
                                <th>Total Spent</th>
                                <th>Country</th>
                            </tr>
                        </thead>

                        <tbody className="bg-white">
                            <tr>
                                <td className="red-yellow-gradient-text">QQ-1234Z</td>
                                <td>Ettiene, Clemence</td>
                                <td>123</td>
                                <td>999,999.99 €</td>
                                <td>PT</td>
                            </tr>
                            <tr>
                                <td className="red-yellow-gradient-text">QQ-1234Z</td>
                                <td>Ettiene, Clemence</td>
                                <td>123</td>
                                <td>999,999.99 €</td>
                                <td>PT</td>
                            </tr>
                            <tr>
                                <td className="red-yellow-gradient-text">QQ-1234Z</td>
                                <td>Ettiene, Clemence</td>
                                <td>123</td>
                                <td>999,999.99 €</td>
                                <td>PT</td>
                            </tr>
                            <tr>
                                <td className="red-yellow-gradient-text">QQ-1234Z</td>
                                <td>Ettiene, Clemence</td>
                                <td>123</td>
                                <td>999,999.99 €</td>
                                <td>PT</td>
                            </tr>
                            <tr>
                                <td className="red-yellow-gradient-text">QQ-1234Z</td>
                                <td>Ettiene, Clemence</td>
                                <td>123</td>
                                <td>999,999.99 €</td>
                                <td>PT</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </>
    );
}

export async function getServerSideProps(context: any) {
    const { locale } = context;
    const session = await getSession(context);

    if (!session) {
        return {
            redirect: { destination: `/${locale === 'fr' ? '' : `${locale}/`}auth/signin` }
        };
    }

    return {
        props: {
            session,
            locale,
            messages: {
                ...require(`../../messages/${locale}.json`)
            }
        }
    };
}
