import Head from 'next/head'
import Header from "../components/header/Header";
import Sidebar from "../components/layout/Sidebar";
import { getSession } from "next-auth/client";

// const Home: NextPage = (Props) => {
export default function Home({session} : {session:any}) {
    if (!session) return <></>
    return (
        <div>
            <Head>
                <title>Facebook Clone App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Header */}
            <Header user={session.user} />

            <main>
                {/* Sidebar */}
                <Sidebar user={session.user} />
                {/* Feed */}
                {/* Widgets */}
            </main>
        </div>
    )
}

export async function getServerSideProps(context:any) {
    const { locale } = context;
    // Get the user, if empty redirect to signin
    const session = await getSession(context);
    if (!session) {
        return {
            redirect: { destination: `/${locale}/auth/signin` },
        };
    }

    return {
        props: {
            session,
            locale,
            messages: {
                ...require(`../messages/auth/${locale}.json`),
            },
        }
    }
}

// export default Home
