import Head from 'next/head';
import FullLayout from '../components/layout/FullLayout';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Amadeo CRM</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
        </div>
    );
}
Home.Layout = FullLayout;

export async function getServerSideProps(context: any) {
    const { locale } = context;

    return {
        props: {
            locale,
            messages: {
                ...require(`../messages/${locale}.json`)
            }
        }
    };
}
